USE [PetHealthCareSys]
GO

/* Insert Data to table Service */
INSERT INTO [dbo].[Service] (Name, Description, Duration, Price, CreatedBy, LastUpdatedBy, DeletedBy, CreatedTime, LastUpdatedTime, DeletedTime)
VALUES 
    (N'Kiểm soát bọ chét khi tắm (theo toa)', NULL, 30, 200000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Tư vấn/Đào tạo Hành vi', NULL, 60, 500000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Giấy chứng nhận sức khỏe (Bán hàng & Du lịch)', NULL, 45, 150000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Nội trú và Chăm sóc ban ngày', NULL, 1440, 3000000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Nhập viện', NULL, 1440, 5000000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Hoàn thành các bài kiểm tra đánh giá y tế', NULL, 60, 700000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Phòng thí nghiệm chẩn đoán trong nhà', NULL, 30, 1000000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Vi mạch da liễu', NULL, 30, 800000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Nhận biết', NULL, 15, 50000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Chăm sóc nha khoa', NULL, 60, 1200000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Tư vấn chế độ ăn uống', NULL, 30, 200000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Tiệm thuốc', NULL, 15, 100000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Siêu âm kỹ thuật số', NULL, 45, 1500000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'X-quang kỹ thuật số', NULL, 45, 1200000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Vắc-xin', NULL, 15, 300000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Nội soi sợi quang', NULL, 60, 1800000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL),
    (N'Chương trình chăm sóc sức khỏe', NULL, 1440, 10000000, NULL, NULL, NULL, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), NULL);
GO
